version: '3'

services:
  postgres_tenant:
    image: postgres:12
    container_name: postgres_tenant
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_TENANT_CONFIG_DATABASE=tenant_config
      - POSTGRES_MULTIPLE_DATABASES=multi_tenant_a,multi_tenant_b
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./create-database.sh:/docker-entrypoint-initdb.d/create-database.sh
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge