server:
  port: 8080

spring:
  application:
    name: MultiTenantApp

product-database-lookup-pg:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/product_database_lookup
  username: postgres
  password: password

product-database-tenant-pg:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/%s
  username: postgres
  password: password