server:
  port: 8080

spring:
  application:
    name: MultiTenantApp

app:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/%s
    username: postgres
    password: password